routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/{id}', 'HomeController@show')->name('show')->where(['id' => '[0-9]+']);

Route::prefix('admin')->middleware('auth')->namespace('Admin')->name('admin.')->group(function (){
    Route::get('/', 'DashboardController@index');

    Route::get('/config', 'ConfigController@index')->name('config.index');
    Route::post('/config', 'ConfigController@store')->name('config.store');

    Route::resource('posts', 'PostController');
    Route::resource('tags', 'TagController');
    Route::resource('categories', 'CategoryController');
});

app/Config.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Config extends Model
{
    protected $fillable = [
        'name',
        'value',
    ];
}

app/Http/Controllers/Admin/ConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Config;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ConfigController extends Controller
{
    public function index()
    {
        $config_db = Config::get();
        $config = collect([]);

        $config_db->each(function ($item) use ($config){
            $name = $item->name;
            $config->$name = $item->value;
        });

        return view('admin.config.index', compact(['config']));
    }

    public function store(Request $request)
    {
        Config::updateOrCreate([
            'name' => 'columns'
        ],
        [
            'value' => $request->columns
        ]);
        Config::updateOrCreate([
            'name' => 'per_page'
        ],
        [
            'value' => $request->per_page
        ]);
        return redirect()->route('admin.config.index');
    }
}

resources/views/admin/config/index.blade.php
@extends('adminlte::page')

@section('content')
    <form action="{{ route('admin.config.store') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="columns">Columns</label>
            <select name="columns" id="columns" class="form-control">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="6">6</option>
                <option value="12">12</option>
            </select>
        </div>
        <div class="form-group">
            <label for="per_page">Per page</label>
            <input type="text" name="per_page" class="form-control" id="per_page" value="{{ $config->per_page }}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection